
project_id = "kxjidapjtcxwzpwdomnm"

[auth.external.google]
enabled = true
client_id = "86400450407-7qsc2vqiavkv8agbr74rr8v7718eqamg.apps.googleusercontent.com"
# Keep secret as environment variable
# secret = ""

[functions.gemini-chat]
verify_jwt = true

[functions.document-migration]
verify_jwt = true

[functions.encrypt-data]
verify_jwt = true

[functions.gcp-secrets]
verify_jwt = true
