
project_id = "kxjidapjtcxwzpwdomnm"

[auth.external.google]
enabled = true
# Keep client_id and secret as environment variables
# client_id = ""
# secret = ""

[functions.gemini-chat]
verify_jwt = true

[functions.document-migration]
verify_jwt = true

